{% set version = '0.5.2' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rbokeh
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rbokeh_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rbokeh/rbokeh_{{ version }}.tar.gz
  sha256: d8c47dbd978efce04e5676a3a91d511517a9bb8fe1859c404bfc9ee0f0bf4ec0

build:
  number: 5
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-digest
    - r-gistr
    - r-hexbin
    - r-htmlwidgets >=0.5
    - r-jsonlite
    - r-lazyeval
    - r-magrittr
    - r-maps
    - r-pryr
    - r-scales
  run:
    - r-base
    - r-digest
    - r-gistr
    - r-hexbin
    - r-htmlwidgets >=0.5
    - r-jsonlite
    - r-lazyeval
    - r-magrittr
    - r-maps
    - r-pryr
    - r-scales

test:
  commands:
    - $R -e "library('rbokeh')"           # [not win]
    - "\"%R%\" -e \"library('rbokeh')\""  # [win]

about:
  home: https://hafen.github.io/rbokeh/ https://github.com/bokeh/rbokeh
  license: MIT
  summary: A native R plotting library that provides a flexible declarative interface for creating
    interactive web-based graphics, backed by the Bokeh visualization library <https://bokeh.pydata.org/>.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rbokeh
# Title: R Interface for Bokeh
# Version: 0.5.2
# Authors@R: c( person("Ryan", "Hafen", email = "rhafen@gmail.com", role = c("aut", "cre")), person("Kenton", "Russell", email = "kent.russell@timelyportfolio.com", role = "ctb"), person("Jonathan", "Owen", email = "jonathanro@gmail.com", role = "ctb"), person("Barret", "Schloerke", email = "schloerke@gmail.com", role = "ctb"), person("Saptasrhi", "Guha", email = "saptarshi.guha@gmail.com", role = "ctb"), person("Continuum Analytics, Inc.", role = c("aut", "cph"), comment = "Bokeh library in htmlwidgets/lib, https://bokeh.pydata.org" ))
# Description: A native R plotting library that provides a flexible declarative interface for creating interactive web-based graphics, backed by the Bokeh visualization library <https://bokeh.pydata.org/>.
# URL: https://hafen.github.io/rbokeh/ https://github.com/bokeh/rbokeh
# BugReports: https://github.com/bokeh/rbokeh/issues
# License: MIT + file LICENSE
# LazyData: true
# NeedsCompilation: no
# Imports: htmlwidgets (>= 0.5), maps, methods, jsonlite, digest, hexbin, lazyeval, pryr, magrittr, scales, gistr
# Suggests: testthat, data.table, lattice, lintr, roxygen2 (>= 5.0.0), latticeExtra, knitr, rmarkdown, markdown
# Enhances: shiny (>= 0.12)
# RoxygenNote: 7.1.1
# Encoding: UTF-8
# VignetteBuilder: knitr
# Packaged: 2021-08-03 07:03:31 UTC; hafen
# Author: Ryan Hafen [aut, cre], Kenton Russell [ctb], Jonathan Owen [ctb], Barret Schloerke [ctb], Saptasrhi Guha [ctb], Continuum Analytics, Inc. [aut, cph] (Bokeh library in htmlwidgets/lib, https://bokeh.pydata.org)
# Maintainer: Ryan Hafen <rhafen@gmail.com>
# Repository: CRAN
# Date/Publication: 2021-08-04 00:40:02 UTC
