{% set version = "0.5.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rbokeh
  version: {{ version|replace("-", "_") }}

source:
  fn: rbokeh_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rbokeh_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rbokeh/rbokeh_{{ version }}.tar.gz
  sha256: 48eba3b238cea2b9aa408d8a48c663564292e76f2ab3f603bc671315a4a75a88

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-digest
    - r-ggplot2
    - r-gistr
    - r-hexbin
    - r-htmlwidgets >=0.5
    - r-jsonlite
    - r-lazyeval
    - r-magrittr
    - r-maps
    - r-pryr
    - r-scales
  run:
    - r-base
    - r-digest
    - r-ggplot2
    - r-gistr
    - r-hexbin
    - r-htmlwidgets >=0.5
    - r-jsonlite
    - r-lazyeval
    - r-magrittr
    - r-maps
    - r-pryr
    - r-scales

test:
  commands:
    - $R -e "library('rbokeh')"           # [not win]
    - "\"%R%\" -e \"library('rbokeh')\""  # [win]

about:
  home: https://hafen.github.io/rbokeh https://github.com/bokeh/rbokeh
  license: MIT
  summary: A native R plotting library that provides a flexible declarative interface for creating interactive web-based graphics, backed by the Bokeh visualization library <http://bokeh.pydata.org/>.
  license_family: MIT

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
