appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: X8TcrqUH7IsD0nozl9PmoMfguXO64kylqUaVW/ee6HW1fTNg5AG1C7Y/8yb42nlYTcXVfqzfQ5IRE64MkIJAYgl3bkxHM8Bw2B7EKmn8AvZMODxloTGSYCKo49tVTP1Gx0BQQiKIMjhmkJwicmSKPjCdpsf6xvl251xLdcF78QY6UTM7lOREX5E53eP4ke/cxfC9JrRaF/RxaCOGPVW34icX+6/FKCAPjUUZeABg0zyciRUrG/X3DrVHrFejz+yo4JbxN08L6PwrO6dqQ7WwcqDqhQoOEz4cJQEvGnG1oDscXLX+w/s7GZIsrLzEz7N9T8i3S0aOAjo04IkMD0CxrBWRFZYs0fWH1MD8KYkaNjRjGp4QLDerORQcdokCySV01VAvvPRs1s98hWXh29A6cbwBCeqqZvr+rhD1sc7c8To7XQQgy9vWTTw1G+ph4jd+pMKiuRqz415C93/j5PXkL54ntWNw9UyH60ssd4cG///9pTCYCMIbvFfJl9iDF3HNyHUnBbWLiRFk4aiJLQAfefzGPAFrcYv+dvYDuQkVaocuoVwJPGXwmq3KBCARN5I11h90TlbyKdmj2qYq987klxp5sAG0ObtEs1hNHVGZQO48DLD6mRuWSabJDloZ67z8OQsoooTDvVia+Mz0dcyjXwsZ+2bBUd8/ckytsgdR34E=}
